# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

gem 'codebreaker_smn'
gem 'fasterer'
gem 'rubocop', '~> 0.69.0', require: false
gem 'rubocop-rspec', '~> 1.35.0'
gem 'simplecov', require: false, group: :test
gem 'terminal-table', '~> 1.8.0'
